### ISSUE TITLE
Avosa Social Media Link fix

### ISSUE THREAD

**Issue by Dirklensley** [louisevanderlith/avosaweb#4]
Add the following:

<meta property="og:image" content="" />
 <meta property="og:type" content="" />
 <meta property="og:title" content="" />
 <meta property="og:url" content="" />
 <meta property="og:site_name" content="" />
 <meta property="og:description" content="" />

**Comment by Dirklensley** [comment]
<meta property="og:title" content="" />
<meta property="og:type" content="article" />
<meta property="og:image" content="" />
<meta property="og:url" content="" />
<meta property="og:description" content="" />

**Comment by Dirklensley** [comment]
..<meta property="og:title" content="" />
..<meta property="og:type" content="article" />
..<meta property="og:image" content="" />
..<meta property="og:url" content="" />
..<meta property="og:description" content="" />

**Comment by Dirklensley** [comment]
meta property="og:title" content="" /
meta property="og:type" content="article" /
meta property="og:image" content="" /
meta property="og:url" content="" /
meta property="og:description" content="" /

**Comment by Dirklensley** [comment]
example:

og:title - The title of your object as it should appear within the graph, e.g., "The Rock".
og:type - The type of your object, e.g., "video.movie". Depending on the type you specify, other properties may also be required.
og:image - An image URL which should represent your object within the graph.
og:url - The canonical URL of your object that will be used as its permanent ID in the graph, e.g., "http://www.imdb.com/title/tt0117500/".

**Comment by louisevanderlith** [comment]
Meta tags have been added.
